# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AnalyseEvolutionParcelles
                                 A QGIS plugin
 Analyse automatique de l’évolution des parcelles agricoles entre deux dates, avec calcul des variations de surface et détection des parcelles disparues, conservées ou nouvelles.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-24
        copyright            : (C) 2025 by Abdoulaye Gueye , Dabakh Mbow, Dieumbe Fall
        email                : pabdoulayegueye4@gmail.com,Dieumbe.Fall@USherbrooke.ca , Mbow.Abdou.Aziz.Dabakh@USherbrooke.ca
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AnalyseEvolutionParcelles class from file AnalyseEvolutionParcelles.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .analyse_evolution_parcelles_agricoles import AnalyseEvolutionParcelles
    return AnalyseEvolutionParcelles(iface)
