# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AnalyseEvolutionParcelles
                                 A QGIS plugin
 Analyse automatique de l’évolution des parcelles agricoles entre deux dates, avec calcul des variations de surface et détection des parcelles disparues, conservées ou nouvelles.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-11-24
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Abdoulaye Gueye , Dabakh Mbow, Dieumbe Fall
        email                : pabdoulayegueye4@gmail.com,Dieumbe.Fall@USherbrooke.ca , Mbow.Abdou.Aziz.Dabakh@USherbrooke.ca
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .analyse_evolution_parcelles_agricoles_dialog import AnalyseEvolutionParcellesDialog
import os.path


class AnalyseEvolutionParcelles:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'AnalyseEvolutionParcelles_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Analyse de l’évolution des parcelles agricoles')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('AnalyseEvolutionParcelles', message)
     def remplir_couches(self):

    #Remplit les listes déroulantes Couche T1 et Couche T2 avec les couches polygonales du projet.

        self.dlg.cmbLayerT1.clear()

        self.dlg.cmbLayerT2.clear()

 

        couches = QgsProject.instance().mapLayers().values()

 

        for couche in couches:

            if isinstance(couche, QgsVectorLayer) and couche.geometryType() == QgsWkbTypes.PolygonGeometry:

                self.dlg.cmbLayerT1.addItem(couche.name(), couche.id())

                self.dlg.cmbLayerT2.addItem(couche.name(), couche.id())

    def choisir_fichier_sortie(self):

   

    # Ouvre une boîte de dialogue pour choisir le fichier de sortie et écrit le chemin dans la ligne 'Fichier de sortie'.

   

        fichier, _ = QFileDialog.getSaveFileName(

            self.dlg,

        "Choisir le fichier de sortie",

        "",

        "GeoPackage (*.gpkg);;Shapefile ESRI (*.shp);;Tous les fichiers (*.*)"

    )

 

        if fichier:

        # on affiche le chemin choisi dans la ligne de texte

            self.dlg.lineEditOutput_2.setText(fichier)

 

    def get_layers_selectionnees(self):

        idx_t1 = self.dlg.cmbLayerT1.currentIndex()

        idx_t2 = self.dlg.cmbLayerT2.currentIndex()

 

        if idx_t1 < 0 or idx_t2 < 0:

            return None, None

 

        id_t1 = self.dlg.cmbLayerT1.itemData(idx_t1)

        id_t2 = self.dlg.cmbLayerT2.itemData(idx_t2)

 

        couche_t1 = QgsProject.instance().mapLayer(id_t1)

        couche_t2 = QgsProject.instance().mapLayer(id_t2)

 

        return couche_t1, couche_t2

   

    def preparer_couches(self, couche_t1, couche_t2):

        """

        Vérifie que les couches sont des polygones,

        aligne le CRS de T2 sur T1 si nécessaire,

        et corrige les géométries invalides.

        Retourne (couche_t1_prete, couche_t2_prete) ou (None, None) en cas d'erreur.

        """

 

        # 1) Vérifier que ce sont bien des polygones

        if couche_t1.geometryType() != QgsWkbTypes.PolygonGeometry:

            QMessageBox.critical(

                self.dlg,

                "Erreur",

                f"La couche T1 ({couche_t1.name()}) n'est pas une couche de polygones."

            )

            return None, None

 

        if couche_t2.geometryType() != QgsWkbTypes.PolygonGeometry:

            QMessageBox.critical(

                self.dlg,

                "Erreur",

                f"La couche T2 ({couche_t2.name()}) n'est pas une couche de polygones."

            )

            return None, None

 

        couche_t1_preparee = couche_t1

        couche_t2_preparee = couche_t2

 

        # 2) Vérifier / harmoniser le CRS

        crs_t1 = couche_t1.crs()

        crs_t2 = couche_t2.crs()

 

        if crs_t1 != crs_t2:

            # On reprojette T2 vers le CRS de T1

            try:

                params_reproj = {

                    "INPUT": couche_t2,

                    "TARGET_CRS": crs_t1,

                    "OUTPUT": "memory:"

                }

                res_reproj = processing.run("native:reprojectlayer", params_reproj)

                couche_t2_preparee = res_reproj["OUTPUT"]

            except Exception as e:

                QMessageBox.critical(

                    self.dlg,

                    "Erreur de reprojection",

                    f"Impossible de reprojeter la couche T2 vers le CRS de T1.\n\nDétail : {e}"

                )

                return None, None

 

        # 3) Corriger les géométries invalides

        try:

            res_fix_t1 = processing.run(

                "native:fixgeometries",

                {"INPUT": couche_t1_preparee, "OUTPUT": "memory:"}

            )

            couche_t1_preparee = res_fix_t1["OUTPUT"]

 

            res_fix_t2 = processing.run(

                "native:fixgeometries",

                {"INPUT": couche_t2_preparee, "OUTPUT": "memory:"}

            )

            couche_t2_preparee = res_fix_t2["OUTPUT"]

 

        except Exception as e:

            QMessageBox.critical(

                self.dlg,

                "Erreur de correction",

                f"Impossible de corriger les géométries invalides.\n\nDétail : {e}"

            )

            return None, None

 

        return couche_t1_preparee, couche_t2_preparee




    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/analyse_evolution_parcelles_agricoles/icon.png'
        self.add_action(
            icon_path,
            text=self.tr("Analyse de l’évolution des parcelles agricoles"),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Analyse de l’évolution des parcelles agricoles'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = AnalyseEvolutionParcellesDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
