# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AnalyseEvolutionParcellesDialog
                                 A QGIS plugin
 Analyse automatique de l’évolution des parcelles agricoles entre deux dates, avec calcul des variations de surface et détection des parcelles disparues, conservées ou nouvelles.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-24
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Abdoulaye Gueye , Dabakh Mbow, Dieumbe Fall
        email                : pabdoulayegueye4@gmail.com,Dieumbe.Fall@USherbrooke.ca , Mbow.Abdou.Aziz.Dabakh@USherbrooke.ca
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'analyse_evolution_parcelles_agricoles_dialog_base.ui'))


class AnalyseEvolutionParcellesDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(AnalyseEvolutionParcellesDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
